---

name: opus-mt-zh-en-decoder

gops: [0.123655947]

model: $(home)/opus-mt-zh-en-decoder.onnx

precision: true

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(model)
    --input_shapes "[[1,1],[1,1],[1,1,512],[1,8,511,64],
    [1,8,511,64],[1,8,511,64],[1,8,511,64],[1,8,511,64],
    [1,8,511,64],[1,8,511,64],[1,8,511,64],[1,8,511,64],
    [1,8,511,64],[1,8,511,64],[1,8,511,64]]"
    --mlir $(workdir)/transformed.mlir

BM1684X:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip $(target)
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f32.bmodel
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F16
        --chip $(target)
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f16.bmodel