---

name: WenetEncoder

gops: [1.6]

shapes:
  - [[1, 67, 80], [1], [1, 1], [1, 12, 4, 80, 128], [1, 12, 256, 7], [1, 1, 80]]

model: $(home)/encoder.onnx

runtime_cmp: false

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(model)
    --test_input $(root)/dataset/npz_input/encoder_input.npz
    --input_shapes [$(shape_param)]
    --test_result $(workdir)/$(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

BM1684:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(workdir)/$(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684_f32.bmodel
