---
name: inception_v1
gops: [2.968]
input_shapes: "[1,3,224,224]"

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def  $(home)/deploy.prototxt
    --model_data  $(home)/bvlc_googlenet.caffemodel
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes $(input_shapes)
    --resize_dims 256,256
    --mean 123.675,116.28,103.53
    --scale 0.0171,0.0175,0.0174
    --pixel_format rgb
    --test_result $(workdir)/$(name)_top_outputs.npz
    --mlir $(workdir)/$(name).mlir

# mlir_calibration:
#   run_calibration.py $(workdir)/$(name).mlir
#     --dataset $(imagenet2012_mlir_cali_set)
#     --input_num 100
#     -o $(home)/cali_table

BM1684:
  deploy:
    - model_deploy.py  --mlir $(workdir)/$(name).mlir
      --quantize F32
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(workdir)/$(name)_top_outputs.npz
      --model $(workdir)/$(name)_bm1684_f32.bmodel
    - model_deploy.py  --mlir $(workdir)/$(name).mlir
      --quantize INT8
      --calibration_table $(home)/cali_table
      --quant_input
      --quant_output
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(workdir)/$(name)_top_outputs.npz
      --model $(workdir)/$(name)_bm1684_int8_sym.bmodel
