---

name: mm_resnet50
gops: [2.42]
shapes:
  - [1, 3, 32, 32]

model: $(home)/resnet50.onnx

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(model)
    --input_shapes [$(shape_param)]
    --mean 129.304,124.070,112.434
    --scale 0.0146692093,0.0152923905,0.0142009145
    --pixel_format rgb
    --test_input $(root)/dataset/npz_input/cifar100_img.npy
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/$(name).mlir

mlir_calibration:
  run_calibration.py $(workdir)/$(name).mlir
    --dataset $(cifar100_mlir_cali_set)
    --input_num 200
    -o $(home)/$(name)_cali_table

deploy:
  - model_deploy.py --mlir $(workdir)/$(name).mlir
      --quantize F32
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_$(target)_f32.bmodel
  - model_deploy.py --mlir $(workdir)/$(name).mlir
      --quantize INT8
      --calibration_table $(home)/$(name)_cali_table
      --quant_input
      --quant_output
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.98,0.85
      --model $(workdir)/$(name)_$(target)_int8_sym.bmodel

dataset:
  image_path: $(cifar100_val_set)
  mean: [129.304, 124.070, 112.434]
  scale: [0.0146692093, 0.0152923905, 0.0142009145]

harness:
  type: cifar100_topk
  args:
    - name: FP32
      bmodel: $(workdir)/$(name)_$(target)_f32.bmodel
    - name: INT8
      bmodel: $(workdir)/$(name)_$(target)_int8_sym.bmodel
