---

name: DBNet_totaltext_res50_dcn
gops: 173.82

model: $(home)/totaltext_res50_dcn.pt
batch_sizes: [1, 4, 8]

BM1684X:
  fp_loops:
    - build_env: [  ]
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32

  fp_batch_sizes: $(batch_sizes)

  fp_compile_options:
    python3 -m bmnetp
    --model $(model)
    --net_name $(name)
    --shapes [1,3,224,224]
    --target BM1684X
    --enable_profile True