---

name: DBNet_totaltext_res18_dcn
gops: 95.91

model: $(home)/totaltext_res18_dcn.pt
batch_sizes: [1, 4, 8]

BM1684X:
  fp_loops:
    - build_env: [  ]
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=auto
      fp_outdir_template: "{}b.fp16.compilation"
      prec: FP16

  fp_batch_sizes: $(batch_sizes)

  fp_compile_options:
    python3 -m bmnetp
    --model $(model)
    --net_name $(name)
    --shapes [1,3,224,224]
    --target BM1684X
    --enable_profile True