---

name: retinaface
gops: 88.7

shapes:
  - [1, 3, 640, 640]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/retinaface.onnx
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/$(name).mlir

mlir_calibration:
  run_calibration.py $(workdir)/$(name).mlir
    --dataset $(coco2017_mlir_cali_set)
    --input_num 100
    -o $(home)/cali_table

BM1684:
  deploy:
    - model_deploy.py  --mlir $(workdir)/$(name).mlir
        --quantize F32
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_$(target)_f32.bmodel
    - model_deploy.py  --mlir $(workdir)/$(name).mlir
        --quantize INT8
        --calibration_table $(home)/cali_table
        --quant_input
        --quant_output
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --model $(workdir)/$(name)_bm1684_int8_sym.bmodel
