---

name: sam-vit-base
gops: [984.228]

shapes:
  - [[1, 3, 1024, 1024], [1, 1, 1, 2]]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/$(name).onnx
    --input_shapes [$(shape_param)]
    --test_input $(home)/$(name)_in.npz
    --test_result $(workdir)/$(name)_top_outputs.npz
    --mlir $(workdir)/$(name).mlir

BM1684X:
  deploy:
    - model_deploy.py --mlir $(workdir)/$(name).mlir
      --quantize F32
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(workdir)/$(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_$(target)_f32.bmodel
    - model_deploy.py --mlir $(workdir)/$(name).mlir
      --quantize F16
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(workdir)/$(name)_top_outputs.npz
      --tolerance 0.98,0.82
      --model $(workdir)/$(name)_$(target)_f16.bmodel
